/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Language = IDL.Variant({
  'hindi' : IDL.Null,
  'gujarati' : IDL.Null,
  'english' : IDL.Null,
});
export const Contact = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'language' : Language,
  'message' : IDL.Text,
  'phone' : IDL.Text,
});

export const idlService = IDL.Service({
  'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
  'getContact' : IDL.Func([IDL.Nat], [Contact], ['query']),
  'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
  'incrementVisits' : IDL.Func([], [], []),
  'submitContact' : IDL.Func([IDL.Text, IDL.Text, IDL.Text, Language], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Language = IDL.Variant({
    'hindi' : IDL.Null,
    'gujarati' : IDL.Null,
    'english' : IDL.Null,
  });
  const Contact = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'language' : Language,
    'message' : IDL.Text,
    'phone' : IDL.Text,
  });
  
  return IDL.Service({
    'getAllContacts' : IDL.Func([], [IDL.Vec(Contact)], ['query']),
    'getContact' : IDL.Func([IDL.Nat], [Contact], ['query']),
    'getVisitCount' : IDL.Func([], [IDL.Nat], ['query']),
    'incrementVisits' : IDL.Func([], [], []),
    'submitContact' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, Language],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };